repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
    - id: check-merge-conflict
      name: '[GENERIC] merge conflict check'
    - id: check-symlinks
      name: '[GENERIC] symlink check'
    - id: destroyed-symlinks
      name: '[GENERIC] detect broken symlinks'
    - id: detect-private-key
      name: '[GENERIC] detect private keys uploaded by accident'
    - id: check-case-conflict
      name: '[GENERIC] detect OS file naming case conflicts'
    - id: check-executables-have-shebangs
      name: '[GENERIC] check for shebangs in executable files'
    - id: check-illegal-windows-names
      name: '[GENERIC] detect illegal Windows file names'
    - id: check-yaml
      name: '[YAML] check'

  - repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
      - id: black
        language_version: python

  - repo: https://github.com/pycqa/flake8
    rev: 7.3.0
    hooks:
    - id: flake8

  - repo: https://github.com/DavidAnson/markdownlint-cli2
    rev: v0.18.1
    hooks:
    - id: markdownlint-cli2
      name: '[MARKDOWN] lint'

  - repo: https://github.com/sphinx-contrib/sphinx-lint
    rev: 'v1.0.0'
    hooks:
    - id: sphinx-lint
      name: '[SPHINX/RST] sphinx lint'

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
    - id: end-of-file-fixer
      name: '[GENERIC] newline eof'
    - id: trailing-whitespace
      name: '[GENERIC] remove trailing whitespace'
