version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"

python:
  install:
    - requirements: docs/requirements.txt
    - path: .

sphinx:
  configuration: docs/conf.py

# Optional: Run your doc generator script before Sphinx
build:
  jobs:
    pre_build:
      - python tools/generate_ini_doc_from_scripts.py
