[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "seismic-waveform-factory"
dynamic = ["version"]
description = "Tools for generating and analyzing synthetic seismic waveforms"
authors = [
    { name = "Thomas Ulrich"}
]
readme = "README.md"
license = { text = "MIT" }
requires-python = ">=3.9"
dependencies = [
    "argcomplete",
    "cartopy",
    "geopandas",
    "geopy",
    "h5py",
    "hinetpy",
    "instaseis; python_version >= '3.11'",
    "lxml",
    "matplotlib",
    "networkx",
    "numpy",
    "obspy",
    "pandas",
    "pyproj",
    "pyprop8",
    "pyvista",
    "requests",
    "ruamel.yaml",
    "scikit-learn",
    "scipy",
    "seissolxdmf",
    "shapely",
    "tqdm",
    "trimesh",
    "vtk",
]

[project.optional-dependencies]
test = [
    "pytest",
    "pytest-cov",
]

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools]
include-package-data = true

[tool.setuptools_scm]
version_scheme = "post-release"
local_scheme = "dirty-tag"

[project.scripts]
swf = "seismic_waveform_factory.cli:main"


[tool.pytest.ini_options]
# Automatically run with coverage on your core source directory
addopts = "--cov=seismic_waveform_factory --cov-report=term-missing --cov-report=html"
testpaths = ["test"]

[tool.coverage.run]
# Tells coverage to look at the source files, not the installed package
source = ["src/seismic_waveform_factory"]

[tool.coverage.report]
# Exclude standard boilerplate from your coverage metrics
exclude_lines = [
    "pragma: no cover",
    "def __repr__",
    "if __name__ == .__main__.:",
    "raise NotImplementedError"
]
