general:
  setup_name: 7000lsze_global
  figure_extension: pdf
  font_size: 8
  relative_offset: 0.0
  global_legend_labels: []
  projection: +proj=tmerc +datum=WGS84 +k=0.9996 +lon_0=78.65 +lat_0=41.26
  hypocenter: {lon: 78.6538, lat: 41.2555, depth_in_km: 13.0, onset: '2024-01-22T18:09:04.340Z'}
  client: iris
  line_colors: [grey, r, b, pink, g]
  line_widths: [1.0]
  path_observations: ./global_observations
  fault_file: output/dyn-kinmod_extractedlast-fault.xdmf
  misfit: cross-correlation
synthetics:
  - type: instaseis
    name: instaseis_1
    source_files: [ mps_regional/PointSourceFile_dyn_0000_coh0.25_1.0_B0.9_C0.1_R0.55_extracted_dx20.0_nz4.h5,
      mps_regional/PointSourceFile_dyn_0001_coh0.25_1.0_B0.9_C0.1_R0.6_extracted_dx20.0_nz4.h5]
    db: syngine://prem_a_2s
    mode: green_functions
    path_computed_synthetics: ./computed_synthetics
waveform_plots:
  - type: p
    enabled: true
    misfit: auto
    synthetics: [instaseis_1]
    kind: displacement
    stations: [G.RER, GE.TIRR, II.FFC, IU.DAV, IU.FURI, IU.INCN, IU.TATO, IU.YAK,
      II.MBAR, IU.COLA]
    t_before: 20.0
    t_after: 36.54
    taper: true
    normalize: false
    shift_match_correlation: true
    scaling: 1.0
    filter_tmin: 10.0
    filter_tmax: 200.0
    ncol_per_component: 2
    annotations:
      fields: [distance, azimuth, misfit]
      distance_unit: auto
    components: [Z]
  - type: sh
    enabled: true
    misfit: auto
    synthetics: [instaseis_1]
    kind: displacement
    stations: [G.RER, GE.TIRR, II.FFC, IU.DAV, IU.FURI, IU.INCN, IU.TATO, IU.YAK,
      II.MBAR, IU.COLA]
    t_before: 20.0
    t_after: 36.54
    taper: true
    normalize: false
    shift_match_correlation: true
    scaling: 1.0
    filter_tmin: 10.0
    filter_tmax: 200.0
    ncol_per_component: 2
    annotations:
      fields: [distance, azimuth, misfit]
      distance_unit: auto
    components: [T]
  - type: generic
    enabled: true
    misfit: auto
    synthetics: [instaseis_1]
    kind: displacement
    stations: [G.RER, GE.TIRR, II.FFC, IU.DAV, IU.FURI, IU.INCN, IU.TATO, IU.YAK,
      II.MBAR, IU.COLA]
    t_before: 0.0
    t_after: 3000.0
    taper: true
    normalize: false
    shift_match_correlation: true
    scaling: 1.0
    filter_tmin: 100.0
    filter_tmax: 500.0
    ncol_per_component: 1
    annotations:
      fields: [distance, azimuth, misfit]
      distance_unit: auto
    components: [E, N, Z]
