name: Build and Generate Docs

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install sphinx sphinx_rtd_theme

      - name: Generate INI documentation
        run: |
          python tools/generate_ini_doc_from_scripts.py scripts/config_schema.py docs

      - name: Build Sphinx HTML docs
        run: |
          cd docs
          make html
